select top 20
	* 
from 
	customer_shopping_behavior

-- what is the total revenue generated by male vs female customers?


select
	gender,
	sum(purchase_amount) as revenue
from
	customer_shopping_behavior
group by 
	gender


-- which customer used discount but still spent more than the average purchase amount?


select
	*
from 
	customer_shopping_behavior
where
	discount_applied = 'Yes' and purchase_amount > (select avg(purchase_amount) from customer_shopping_behavior)


-- which are the top 5 products with highest average review rating?


select top 5
	item_purchased,
	round(avg(review_rating),2) as average_review_rating
from
	customer_shopping_behavior
group by item_purchased
order by avg(review_rating) desc


-- compare the average purchase amounts between standard and express shipping


select 
	shipping_type,
	avg(purchase_amount) as average_purchase_amount
from
	customer_shopping_behavior
where shipping_type in ('Standard','Express')
group by shipping_type


-- do subscribed customers spend more? compare average spend and total revenue between subscribers and non-subscribers


select
	subscription_status,
	count(customer_id) as total_customers,
	avg(purchase_amount) as average_purchase_amount,
	sum(purchase_amount) as total_purchase_amount
from
	customer_shopping_behavior
group by 
	subscription_status


-- which 5 products have the highest percentage of purchases with discount applied?


select top 5
	item_purchased,
	100*sum(case when discount_applied = 'Yes' then 1 else 0 end)/count(*) as discount_rate
from
	customer_shopping_behavior
group by item_purchased
order by discount_rate desc


-- segment customers into new, returning and loyal based on thier total number of previous purchases, and show the count of each segments


with cte1 as (
select 
	previous_purchases,
	case
		when previous_purchases between 1 and 3 then 'New'
		when previous_purchases between 4 and 15 then 'Returning'
		else 'Loyal'
		end as customer_type
from
	customer_shopping_behavior
)

select
	customer_type,
	count(*) as 'Total Customers'
from cte1
group by customer_type
order by [Total Customers] desc


-- what are the top 3 most purchased products within each category


with item_counts as(
select
	category,
	item_purchased,
	count(customer_id) as total_orders,
	row_number() over(partition by category order by count(customer_id) desc) as item_rank
from
	customer_shopping_behavior
group by 
	category,item_purchased
)

select
	item_rank,
	category,
	item_purchased,
	total_orders
from 
	item_counts
where
	item_rank <=3


-- are customers who are repeat buyers(more than 5 previous purchases) also likely to subscribe?

select
	subscription_status,
	count(customer_id) as repeat_buyers
from
	customer_shopping_behavior
where
	previous_purchases > 5
group by
	subscription_status


-- what is the revenue contribution of each age group

select
	age_group,
	sum(purchase_amount) as total_revenue
from 
	customer_shopping_behavior
group by age_group
order by total_revenue desc